//Teste de Requisições REST
@baseURL = http://localhost:3000
@id = 63559b032dea6826268a985c

###
// GET -
GET {{baseURL}}/pratos
Content-Type: application/json

###
// GET -
GET {{baseURL}}/pratos/{{id}}
Content-Type: application/json

###
// POST -
POST {{baseURL}}/pratos
Content-Type: application/json

{
    "nome": "Filé de Saint Peter",
    "preco": 19.90,
    "descricao": "Arroz, Feijão",
    "diasSemana":["seg", "sex"],
    "acompanhamentos": ["fritas", "legumes"],
    "status":"ativo"
}

###
// PUT -
PUT {{baseURL}}/pratos
Content-Type: application/json

{
    "_id":"6359be88c7e644a7de814876",
    "nome": "Bife ao Molho Madeira",
    "preco": 25.50,
    "descricao": "Arroz, Feijão, Bife",
    "diasSemana":["seg", "sex"],
    "acompanhamentos": ["fritas", "farofa"],
    "status":"ativo"
}

###
// DELETE -
DELETE {{baseURL}}/pratos/{{id}}
Content-Type: application/json